backend:
  name: github
  repo: cvbiju/eltoro-website # The GitHub repository
  branch: main # Branch to update
  # Optional: use a specific sub-directory if the admin shouldn't have access to the whole repo
  # base_url: https://my-custom-auth-server.com # Required for GitHub OAuth if not using Netlify Identity

# This folder is where uploaded files will be saved relative to where the site is built
media_folder: "public/assets/images"
# This is the path the front-end code will use to reference the uploaded files
public_folder: "./assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page Settings"
        name: "homepage"
        file: "public/admin/settings.json"
        fields:
          - {label: "Hero Background Image", name: "hero_bg", widget: "image", required: false}
          - {label: "Who We Are Main Image", name: "who_we_are_img", widget: "image"}

