backend:
  name: git-gateway
  branch: main # Branch to update

# This folder is where uploaded files will be saved relative to where the site is built
media_folder: "public/assets/images"
# This is the path the front-end code will use to reference the uploaded files
public_folder: "./assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page Settings"
        name: "homepage"
        file: "public/admin/settings.json"
        fields:
          - {label: "Hero Background Image", name: "hero_bg", widget: "image", required: false}
          - {label: "Who We Are Main Image", name: "who_we_are_img", widget: "image"}

